@echo off
echo Compiling demo.mc to assembly...
python src/main.py -S examples/demo.mc -o demo.s
echo Assembling...
nasm -f win64 demo.s -o demo.obj
echo Linking...
gcc demo.obj -o demo.exe -lc
echo Running demo...
demo.exe
echo Exit code: %errorlevel%